apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-quarkus
spec:
  selector:
    matchLabels:
      name: java-quarkus
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        name: java-quarkus
    spec:
      containers:
        - name: java-quarkus
          image: java-quarkus:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: java-quarkus-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8080
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 2
            failureThreshold: 5
