apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-quarkus

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - backend

configMapGenerator:
  - name: rust-config
    literals:
      - BACKEND_JWKS_URL=http://jwks:8500/.well-known/jwks.json
      - MP_JWT_VERIFY_ISSUER=sample-issuer
      - MP_JWT_VERIFY_AUDIENCES=sample-audience
      - QUARKUS_REST_CLIENT_FETCH_URL=http://fetch-api:8500
      - QUARKUS_REST_CLIENT_PUSH_URL=http://push-api:8500
