apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-backend
spec:
  selector:
    matchLabels:
      name: java-spring-backend
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        name: java-spring-backend
    spec:
      containers:
        - name: java-spring-backend
          image: 204306537988.dkr.ecr.eu-north-1.amazonaws.com/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
