services:
  database:
    image: "postgres:15.4"
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=nest-db-user
      - POSTGRES_PASSWORD=nest-db-password
    ports:
      - "5432:5432"
    networks:
      - docker-net

  database-setup:
    image: flyway/flyway:10
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/nest
      - FLYWAY_SCHEMAS=nest
      - FLYWAY_USER=nest-db-user
      - FLYWAY_PASSWORD=nest-db-password
    volumes:
      - ./kustomize/environment/local/resources/flyway:/flyway/sql/migrations
    depends_on:
      - database
    networks:
      - docker-net

  service-mock:
    image: "spectolabs/hoverfly:v1.6.3"
    command: -webserver -log-level warn -import /simulations/jwks.json -import /simulations/steps.json -response-body-files-path /simulations
    volumes:
      - ./kustomize/environment/local/hoverfly/resources:/simulations
    ports:
      - "8500:8500"
    networks:
      - docker-net

  app:
    build: .
    image: "nest:latest"
    environment:
      - AUTH_JWT_JWKS_URL=http://service-mock:8500/.well-known/jwks.json
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - DB_CONNECTION=postgresql://nest-db-user:nest-db-password@database:5432/nest
      - STEPS_URL=http://service-mock:8500
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
        reservations:
          cpus: '0.250'
          memory: 500M
    depends_on:
      - database
      - database-setup
      - service-mock
    networks:
      - docker-net

networks:
  docker-net:
