apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  selector:
    matchLabels:
      app: go
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: go
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8082
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8082
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8082
            periodSeconds: 2
            failureThreshold: 5
