apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: go-database-secrets
    literals:
      - POSTGRES_USER=go-db-user
      - POSTGRES_PASSWORD=go-db-password
