apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: nest-database-secrets
    literals:
      - POSTGRES_USER=nest-db-user
      - POSTGRES_PASSWORD=nest-db-password
