apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  selector:
    matchLabels:
      name: nest-backend
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        name: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
