apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-wiremock
spec:
  replicas: 3
  selector:
    matchLabels:
      name: rust-wiremock
  template:
    metadata:
      labels:
        name: rust-wiremock
    spec:
      containers:
        - name: rust-wiremock
          image: rust-wiremock
          ports:
            - containerPort: 8888
