apiVersion: v1
kind: Service
metadata:
  name: rust-wiremock
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
  selector:
    name: rust-wiremock
---
apiVersion: v1
kind: Service
metadata:
  name: jwks
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
  selector:
    name: rust-wiremock
---
apiVersion: v1
kind: Service
metadata:
  name: steps
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
  selector:
    name: rust-wiremock
