apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust
spec:
  selector:
    matchLabels:
      app: rust
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rust
    spec:
      initContainers:
        - command:
            - flyway
            - migrate
          image: flyway/flyway:9.17
          imagePullPolicy: IfNotPresent
          name: flyway-migrate
          envFrom:
            - configMapRef:
                name: rust-flyway-config
            - secretRef:
                name: rust-flyway-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1000Mi"
          volumeMounts:
            - name: flyway-migrations-volume
              mountPath: /flyway/sql/schema
              readOnly: true
      containers:
        - name: rust
          image: rust
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8081
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8081
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8081
            periodSeconds: 2
            failureThreshold: 5
      volumes:
        - name: flyway-migrations-volume
          configMap:
            name: rust-flyway-migrations
