apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust
spec:
  selector:
    matchLabels:
      app: rust
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: rust
    spec:
      containers:
        - name: rust
          image: rust
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "25m"
              memory: "20Mi"
            limits:
              cpu: "100m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8081
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8081
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8081
            periodSeconds: 2
            failureThreshold: 5
