apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  selector:
    matchLabels:
      app: quarkus
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          image: quarkus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8083
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8083
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8083
            periodSeconds: 2
            failureThreshold: 5
