apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest
spec:
  selector:
    matchLabels:
      app: nest
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest
          image: 204306537988.dkr.ecr.eu-north-1.amazonaws.com/nest:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nest-config
            - secretRef:
                name: nest-secrets
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /health/started
              port: 8080
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 2
            failureThreshold: 5
