apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: rust-database-secrets
    literals:
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=database_password
