apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: rust-database-secrets
    literals:
      - POSTGRES_USER=rust-db-user
      - POSTGRES_PASSWORD=rust-db-password
