apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-spring

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - backend

configMapGenerator:
  - name: java-spring-config
    literals:
      - AUTH_JWT_JWKS_URL=http://jwks:8500
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - BACKEND_FETCH_URL=http://fetch-api:8500
      - BACKEND_PUSH_URL=http://push-api:8500
