apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: quarkus-database-secrets
    literals:
      - POSTGRES_USER=quarkus-db-user
      - POSTGRES_PASSWORD=quarkus-db-password
