apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
  - database
  - wiremock

patchesStrategicMerge:
  - init-container-patch.yaml

configMapGenerator:
  - name: rust-config
    behavior: merge
    literals:
      - AUTH_JWT_JWKS_URL=http://jwks:8888/.well-known/jwks.json
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - DB_HOST=rust-database
      - DB_PORT=5432
      - DB_NAME=rust
      - STEPS_URL=http://steps:8888

  - name: rust-flyway-config
    literals:
      - FLYWAY_URL=jdbc:postgresql://rust-database:5432/rust
      - FLYWAY_SCHEMAS=rust

  - name: rust-flyway-migrations
    files:
      - resources/flyway/V1.00.000__Init.sql
      - resources/flyway/V1.00.001__Data.sql

secretGenerator:
  - name: rust-secrets
    behavior: merge
    literals:
      - DB_USER=rust-db-user
      - DB_PASSWORD=rust-db-password

  - name: rust-flyway-secrets
    literals:
      - FLYWAY_USER=rust-db-user
      - FLYWAY_PASSWORD=rust-db-password
