services:
  rust:
    image: "rust:latest"
    build: .
    environment:
      - AUTH_JWT_JWKS_URL=http://wiremock:8888/.well-known/jwks.json
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=rust
      - DB_USER=rust-db-user
      - DB_PASSWORD=rust-db-password
      - STEPS_URL=http://wiremock:8888
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
        reservations:
          cpus: '0.050'
          memory: 500M
    depends_on:
      - database
      - flyway
      - wiremock
    networks:
      - docker-net

  database:
    image: "postgres:15.4"
    environment:
      - POSTGRES_DB=rust
      - POSTGRES_USER=rust-db-user
      - POSTGRES_PASSWORD=rust-db-password
    ports:
      - "5432:5432"
    networks:
      - docker-net

  flyway:
    image: flyway/flyway:10
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/rust
      - FLYWAY_SCHEMAS=rust
      - FLYWAY_USER=rust-db-user
      - FLYWAY_PASSWORD=rust-db-password
    volumes:
      - ./test/flyway:/flyway/sql/migrations
    depends_on:
      - database
    networks:
      - docker-net

  wiremock:
    image: "wiremock/wiremock:3.3.1"
    command: --container-threads=128 --port=8888
    volumes:
      - ./test/wiremock/files:/home/wiremock/__files
      - ./test/wiremock/mappings:/home/wiremock/mappings
    ports:
      - "8888:8888"
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge
