services:
  database-setup:
    image: flyway/flyway:10
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://$DB_HOST:5432/gmt
      - FLYWAY_SCHEMAS=rust
      - FLYWAY_USER=gmt
      - FLYWAY_PASSWORD=GSE2024!
    volumes:
      - ./kustomize/environment/local/resources/flyway:/flyway/sql/migrations

    networks:
      - docker-net

  app:
    image: "rust:latest"
    build: .
    environment:
      - AUTH_JWT_JWKS_URL=http://$SERVICE_MOCK_HOST_PORT/.well-known/jwks.json
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - DB_HOST=$DB_HOST
      - DB_PORT=5432
      - DB_NAME=gmt
      - DB_USER=gmt
      - DB_PASSWORD=GSE2024!
      - STEPS_URL=http://$SERVICE_MOCK_HOST_PORT
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
        reservations:
          cpus: '0.250'
          memory: 500M
    depends_on:
      - database-setup
    networks:
      - docker-net

networks:
  docker-net:
