---
name: Rust K6 Load Test Scenario
author: Andreas Weber <andreas.weber@qaware.de>
description: Simple Webservice accessing DB and (mocked) webservice. Built in rust.
compose-file: !include docker-compose.yaml

services:
  rust-database:
    # Ensure db is running before flyway is started
    setup-commands:
      - sleep 10
  rust-flyway:
    entrypoint: "/bin/sh"
    setup-commands:
      - flyway migrate
  rust-wiremock:
    # This command is needed, cause the container needs a boot time to work
    setup-commands:
      - sleep 10
  rust-k6:
    image: "grafana/k6:0.47.0"
    entrypoint: "/bin/sh"
    networks:
      - rust-docker-net

flow:
  - name: Run Load Tests
    container: rust-k6
    commands:
      - type: console
        command: k6 run /tmp/repo/test/k6/script.js
        note: Run k6 load test
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true


