apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
  - database
  - wiremock
  - namespace.yaml

patchesStrategicMerge:
  - init-container-patch.yaml

configMapGenerator:
  - name: quarkus-config
    behavior: merge
    literals:
      - SAMPLE_JWKS_URL=http://jwks:8888
      - MP_JWT_VERIFY_ISSUER=sample-issuer
      - MP_JWT_VERIFY_AUDIENCES=sample-audience
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-database:5432/quarkus
      - QUARKUS_REST_CLIENT_STEPS_URL=http://steps:8888

  - name: quarkus-flyway-config
    literals:
      - FLYWAY_URL=jdbc:postgresql://quarkus-database:5432/quarkus
      - FLYWAY_SCHEMAS=quarkus

  - name: quarkus-flyway-migrations
    files:
      - resources/flyway/V1.00.000__Init.sql
      - resources/flyway/V1.00.001__Data.sql

secretGenerator:
  - name: quarkus-secrets
    behavior: merge
    literals:
      - QUARKUS_DATASOURCE_USERNAME=quarkus-db-user
      - QUARKUS_DATASOURCE_PASSWORD=quarkus-db-password

  - name: quarkus-flyway-secrets
    literals:
      - FLYWAY_USER=quarkus-db-user
      - FLYWAY_PASSWORD=quarkus-db-password
