apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../local

patchesStrategicMerge:
  - deployment-patch.yaml
