services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: "go:latest"
    environment:
      - AUTH_JWT_JWKS_URL=http://backend:8500
      - AUTH_JWT_EXPECTED_ISSUER=sample-issuer
      - AUTH_JWT_EXPECTED_AUDIENCE=sample-audience
      - BACKEND_FETCH_URL=http://backend:8500
      - BACKEND_PUSH_URL=http://backend:8500
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
    depends_on:
      - backend
    networks:
      - docker-net

  backend:
    build: ../../tools/backend
    image: "backend:latest"
    ports:
      - "8500:8500"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
    networks:
      - docker-net

networks:
  docker-net:
