services:
  database:
    image: "postgres:15.4"
    environment:
      - POSTGRES_DB=quarkus
      - POSTGRES_USER=quarkus-db-user
      - POSTGRES_PASSWORD=quarkus-db-password
    ports:
      - "5432:5432"
    networks:
      - docker-net

  database-setup:
    image: flyway/flyway:10
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://quarkus-database:5432/quarkus
      - FLYWAY_SCHEMAS=quarkus
      - FLYWAY_USER=quarkus-db-user
      - FLYWAY_PASSWORD=quarkus-db-password
    volumes:
      - ./kustomize/environment/local/resources/flyway:/flyway/sql/migrations
    depends_on:
      - database
    networks:
      - docker-net

  service-mock:
    image: "wiremock/wiremock:3.3.1"
    command: --container-threads=128 --port=8888
    volumes:
      - ./kustomize/environment/local/wiremock/image/files:/home/wiremock/__files
      - ./kustomize/environment/local/wiremock/image/mappings:/home/wiremock/mappings
    ports:
      - "8888:8888"
    networks:
      - docker-net

  app:
    build:
      dockerfile: src/main/docker/Dockerfile
      context: .
    image: "quarkus:latest"
    environment:
      - SAMPLE_JWKS_URL=http://quarkus-wiremock:8888
      - MP_JWT_VERIFY_ISSUER=sample-issuer
      - MP_JWT_VERIFY_AUDIENCES=sample-audience
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-database:5432/quarkus
      - QUARKUS_DATASOURCE_USERNAME=quarkus-db-user
      - QUARKUS_DATASOURCE_PASSWORD=quarkus-db-password
      - QUARKUS_REST_CLIENT_STEPS_URL=http://quarkus-wiremock:8888
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
        reservations:
          cpus: '0.250'
          memory: 500M
    depends_on:
      - database
      - database-setup
      - service-mock
    networks:
      - docker-net

networks:
  docker-net:
#    default driver is bridge, Green Metrics Tool cannot handle compose file with driver set
#    driver: bridge
