services:
  database:
    image: "postgres:15.4"
    environment:
      - POSTGRES_DB=quarkus
      - POSTGRES_USER=quarkus-db-user
      - POSTGRES_PASSWORD=quarkus-db-password
    ports:
      - "5432:5432"
    networks:
      - docker-net

  database-setup:
    image: flyway/flyway:10
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/quarkus
      - FLYWAY_SCHEMAS=quarkus
      - FLYWAY_USER=quarkus-db-user
      - FLYWAY_PASSWORD=quarkus-db-password
    volumes:
      - ./kustomize/environment/local/resources/flyway:/flyway/sql/migrations
    depends_on:
      - database
    networks:
      - docker-net

  service-mock:
    image: "spectolabs/hoverfly:v1.6.3"
    command: -webserver -log-level warn -import /simulations/jwks.json -import /simulations/steps.json -response-body-files-path /simulations
    volumes:
      - ./kustomize/environment/local/hoverfly/resources:/simulations
    ports:
      - "8500:8500"
    networks:
      - docker-net

  app:
    build:
      dockerfile: Dockerfile.jvm
#      dockerfile: Dockerfile.native
      context: .
    image: "quarkus:latest"
#    image: "quarkus-native:latest"
    environment:
      - SAMPLE_JWKS_URL=http://service-mock:8500
      - MP_JWT_VERIFY_ISSUER=sample-issuer
      - MP_JWT_VERIFY_AUDIENCES=sample-audience
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/quarkus
      - QUARKUS_DATASOURCE_USERNAME=quarkus-db-user
      - QUARKUS_DATASOURCE_PASSWORD=quarkus-db-password
      - QUARKUS_REST_CLIENT_STEPS_URL=http://service-mock:8500
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 500M
        reservations:
          cpus: '0.250'
          memory: 500M
    depends_on:
      - database
      - database-setup
      - service-mock
    networks:
      - docker-net

networks:
  docker-net:
#    default driver is bridge, Green Metrics Tool cannot handle compose file with driver set
#    driver: bridge
