---
name: Quarkus K6 Load Test Scenario Slim
author: Andreas Weber <andreas.weber@qaware.de>
description: Simple Webservice accessing DB and (mocked) webservice. Built in quarkus.
compose-file: !include docker-compose-slim.yaml

services:
  database-setup:
    # use sleep as entry point. If we directly pass migrate to the entrypoint flyway the container stops after execution
    entrypoint: sleep
    command: infinity
    # start flyway migrate explicitly
    setup-commands:
      - flyway migrate
  app:
    build:
      dockerfile: Dockerfile.jvm
      # use the following line for native execution
      # dockerfile: Dockerfile.native
    setup-commands:
    # This command is needed, cause the container needs a boot time to work
      - sleep 60

flow:
  - name: Run Load Tests
    container: database-setup
    commands:
      - type: console
        command: sleep 300
        note: Run load test manually now
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true

